### ISSUE TITLE
subversion 1.14.5 swig/ruby binding test failure with test-unit 3.6.5

### ISSUE THREAD

**Issue by mtasaka** [test-unit/test-unit#276]
subversion 1.14.5 swig/ruby binding test fails with test-unit 3.6.5:

```
cd /builddir/build/BUILD/subversion-1.14.5-build/subversion-1.14.5/subversion/bindings/swig/ruby; \
  check_rb() { \
    /usr/bin/ruby -I /builddir/build/BUILD/subversion-1.14.5-build/subversion-1.14.5/subversion/bindings/swig/ruby /builddir/build/BUILD/subversion-1.14.5-build/subversion-1.14.5/subversion/bindings/swig/ruby/test/run-test.rb "$@"; \
  }; \
  if check_rb --help 2>&1 | grep -q -- --collector; then \
    check_rb --collector=dir --verbose=verbose; \
  elif [ "3" -eq 1 -a "4" -lt 9 ] ; then \
    check_rb --verbose=verbose; \
  else \
    check_rb; \
          fi
Loaded suite .
Started
SvnClientTest: 

Finished in 0.000259439 seconds.
-------------------------------------------------------------------------------
0 tests, 0 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------
0.00 tests/s, 0.00 assertions/s/builddir/build/BUILD/subversion-1.14.5-build/subversion-1.14.5/subversion/bindings/swig/ruby/test/test-unit-ext/priority.rb:114:in 'run': wrong number of arguments (given 2, expected 1) (ArgumentError)
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:68:in 'Test::Unit::TestSuiteRunner#run_test'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:60:in 'block in Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:59:in 'Array#each'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:59:in 'Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:37:in 'Test::Unit::TestSuiteRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/testsuite.rb:52:in 'Test::Unit::TestSuite#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:68:in 'Test::Unit::TestSuiteRunner#run_test'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:60:in 'block in Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:59:in 'Array#each'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:59:in 'Test::Unit::TestSuiteRunner#run_tests'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:37:in 'Test::Unit::TestSuiteRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/testsuite.rb:52:in 'Test::Unit::TestSuite#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:72:in 'Test::Unit::UI::TestRunnerMediator#run_suite'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:49:in 'block (3 levels) in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:44:in 'Kernel#catch'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:44:in 'block (2 levels) in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/test-suite-runner.rb:17:in 'Test::Unit::TestSuiteRunner.run_all_tests'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:43:in 'block in Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:107:in 'Test::Unit::UI::TestRunnerMediator#with_listener'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnermediator.rb:42:in 'Test::Unit::UI::TestRunnerMediator#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunner.rb:40:in 'Test::Unit::UI::TestRunner#start_mediator'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunner.rb:25:in 'Test::Unit::UI::TestRunner#start'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/ui/testrunnerutilities.rb:24:in 'Test::Unit::UI::TestRunnerUtilities#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/autorunner.rb:492:in 'block in Test::Unit::AutoRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/autorunner.rb:548:in 'Test::Unit::AutoRunner#change_work_directory'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/autorunner.rb:491:in 'Test::Unit::AutoRunner#run'
	from /usr/share/gems/gems/test-unit-3.6.5/lib/test/unit/autorunner.rb:67:in 'Test::Unit::AutoRunner.run'
	from /builddir/build/BUILD/subversion-1.14.5-build/subversion-1.14.5/subversion/bindings/swig/ruby/test/run-test.rb:51:in '<main>'

make: *** [Makefile:976: check-swig-rb] Error 1
```

https://github.com/apache/subversion/blob/c828a37af875249916a452481cae96df83dc67ea/subversion/bindings/swig/ruby/test/test-unit-ext/priority.rb#L114-L116

Looks like this is similar with
https://github.com/ruby-gettext/gettext/issues/109
and perhaps this is because of
https://github.com/test-unit/test-unit/pull/263

Can test-unit behavior be compatible with 3.6.2?

**Comment by kou** [comment]
Oh, it was a file I wrote 16 years ago...
We can remove the file from Subversion because the feature is included in test-unit.
But let's improve backward compatibility instead.
