### ISSUE TITLE
testrunner - NoMethodError: undefined method `include?'

### ISSUE THREAD

**Issue by btatnall** [test-unit/test-unit#66]
Hi,

I'm seeing the stacktrace below using this enviroment.
- jruby 1.7.4 (1.9.3p392) 2013-05-16 2390d3b on OpenJDK 64-Bit Server VM 1.6.0_27-b27 [linux-amd64]
- test-unit 2.5.5
- rails 3.2.15

Stacktrace:

```
NoMethodError: undefined method `include?' for nil:NilClass
    output_fault_in_detail at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/console/testrunner.rb:187
  output_progress_in_detail at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/console/testrunner.rb:434
                  add_fault at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/console/testrunner.rb:93
                      call at org/jruby/RubyMethod.java:134
                      call at org/jruby/RubyProc.java:255
          notify_listeners at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/util/observable.rb:78
                      each at org/jruby/RubyArray.java:1617
          notify_listeners at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/util/observable.rb:78
              with_listener at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnermediator.rb:96
                      call at org/jruby/RubyProc.java:255
          notify_listeners at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/util/observable.rb:78
                      each at org/jruby/RubyArray.java:1617
          notify_listeners at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/util/observable.rb:78
              notify_fault at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testresult.rb:121
                add_failure at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/failure.rb:142
                add_failure at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/failure.rb:119
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/activesupport-3.2.15/lib/active_support/testing/setup_and_teardown.rb:78
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/activesupport-3.2.15/lib/active_support/testing/setup_and_teardown.rb:70
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/activesupport-3.2.15/lib/active_support/testing/setup_and_teardown.rb:69
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/activesupport-3.2.15/lib/active_support/testing/setup_and_teardown.rb:68
                  run_test at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:121
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:53
                  run_test at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:121
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:53
                  run_test at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:121
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/testsuite.rb:53
                  run_suite at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnermediator.rb:65
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnermediator.rb:44
              with_listener at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnermediator.rb:100
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnermediator.rb:40
            start_mediator at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunner.rb:40
                      start at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunner.rb:25
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/ui/testrunnerutilities.rb:24
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/autorunner.rb:409
      change_work_directory at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/autorunner.rb:465
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/autorunner.rb:408
                        run at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit/autorunner.rb:59
                    (root) at /home/tipair/.rvm/gems/jruby-1.7.4@nerd/gems/test-unit-2.5.5/lib/test/unit.rb:502
```

I'm not sure what other information you'll need.

Thanks.

**Comment by btatnall** [comment]
#ancestors won't work for this exception because it is a java object:

    >> p java.sql.BatchUpdateException.new.ancestors
    NoMethodError: undefined method `ancestors' for java.sql.BatchUpdateException:Java::JavaSql::BatchUpdateException
      from (irb):3:in `evaluate'
      from org/jruby/RubyKernel.java:1119:in `eval'
      from org/jruby/RubyKernel.java:1519:in `loop'
      from org/jruby/RubyKernel.java:1282:in `catch'
      from org/jruby/RubyKernel.java:1282:in `catch'
      from /home/tipair/.rvm/gems/jruby-1.7.10@nerd/gems/railties-3.2.16/lib/rails/commands/console.rb:47:in `start'
      from /home/tipair/.rvm/gems/jruby-1.7.10@nerd/gems/railties-3.2.16/lib/rails/commands/console.rb:8:in `start'
      from /home/tipair/.rvm/gems/jruby-1.7.10@nerd/gems/railties-3.2.16/lib/rails/commands.rb:41:in `(root)'
      from org/jruby/RubyKernel.java:1083:in `require'
      from script/rails:6:in `(root)'


Here is the java class hierarchy:

    >> klass = java.sql.BatchUpdateException.new.getClass
    => class java.sql.BatchUpdateException
    >> while klass != nil; next_klass = klass.getSuperclass; puts next_klass; klass = next_klass; end
    java.sql.SQLException
    java.lang.Exception
    java.lang.Throwable
    java.lang.Object

    => nil

**Comment by kou** [comment]
Don't call `.new`. Please use class object: `p java.sql.BatchUpdateException.ancestors`.

**Comment by kares** [comment]
this has been fixed ever since, right? ... askin cause test-unit 2.5.5 is used with activerecord-jdbc-adapter

**Comment by kou** [comment]
Could you provide a test case that reproduces this problem?
