### ISSUE TITLE
Test::Unit::TestCase#name does not work

### ISSUE THREAD

**Issue by voxik** [test-unit/test-unit#92]
There are two reasons I believe that the $SUBJECT doesn't work:

1) Trying to fix erubis test suite, this line fails for me:

https://github.com/kwatch/erubis/blob/master/test/test-main.rb#L219

with following error:

~~~
Error: 
: NoMethodError: undefined method `gsub' for nil:NilClass
/builddir/build/BUILD/usr/share/gems/gems/erubis-2.7.0/test/test-main.rb:219:in `_with_dummy_file'
/builddir/build/BUILD/usr/share/gems/gems/erubis-2.7.0/test/test-main.rb:237:in `test_syntax1'
     234:     @options  = '-z'
     235:     _test()
     236:     #
  => 237:     _with_dummy_file do |filepath|
     238:       actual = `erubis #{@options} #{filepath}`
     239:       assert_equal @expected, actual
     240:     end
~~~

2) Trying the -n option:

~~~
$ ruby -I.:lib -e "Dir.glob('./test/test-main.rb').each {|t| require t}" -- -n=/.*/
/usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:219:in `block (3 levels) in options': undefined method `gsub' for nil:NilClass (NoMethodError)
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:45:in `[]'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:45:in `block in include?'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:44:in `each'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:44:in `include?'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:19:in `block in add_suite'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `each'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `find_all'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:18:in `add_suite'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:65:in `block in add_test_case'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:62:in `each'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:62:in `add_test_case'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:38:in `block in add_test_cases'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:37:in `each'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector.rb:37:in `add_test_cases'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/collector/descendant.rb:13:in `collect'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:84:in `block in <class:AutoRunner>'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:394:in `[]'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:394:in `run'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb:59:in `run'
	from /usr/share/gems/gems/test-unit-3.0.9/lib/test/unit.rb:502:in `block (2 levels) in <top (required)>'
~~~

Which fail on line

https://github.com/test-unit/test-unit/blob/master/lib/test/unit/autorunner.rb#L219

where the #name method is used again.

**Comment by kou** [comment]
It's not a test-unit problem: https://github.com/kwatch/erubis/blob/master/test/test.rb#L26

**Comment by voxik** [comment]
There is no MiniTest in the call stack at all. Actually, there is not MiniTest on the system at all. So whose problem would it be if not test-units?

**Comment by kou** [comment]
It's a problem of Erubis.
Did you see the code? The code is for minitest. (To be precise, the code is for Test::Unit compatible API of minitest.) So it doesn't need for test-unit gem. If you just remove the code, tests of Erubis will work well.
