### ISSUE TITLE
Bang (!) causes segmentation fault in dup-ed classes

### ISSUE THREAD

**Issue by rap-kasta** [test-unit/test-unit#93]
Bare-minimum segmentation fault reproduction code:

```ruby
require 'test/unit'

class Hell
  class << self
    def hot?
      !false
    end
  end
end

puts Hell.dup.hot?.inspect
```

When `test-unit 3.0.x` used this code will hang up with segmentation fault (see below), `test-unit 2.5.5` works fine. Tested on stable `ruby 2.2.0`. I understand that this is may be an issue on MRI side, but I can reproduce bug only with `test-unit`.

```bash
[rk@soft24-dev-arch docflow]$ ruby hell_test.rb
hell_test.rb:6: [BUG] Segmentation fault at 0x00000000000010
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0003 p:0008 s:0009 e:000007 METHOD hell_test.rb:6
c:0002 p:0032 s:0005 E:000100 EVAL   hell_test.rb:11 [FINISH]
c:0001 p:0000 s:0002 E:0018a0 TOP    [FINISH]

-- Ruby level backtrace information ----------------------------------------
hell_test.rb:11:in `<main>'
hell_test.rb:6:in `hot?'

-- Machine register context ------------------------------------------------
 RIP: 0x00007f5cafe6a9c8 RBP: 0x00007fff1e970ae0 RSP: 0x00007fff1e970a80
 RAX: 0x0000000001e962b0 RBX: 0x0000000000000008 RCX: 0x0000000002023f90
 RDX: 0x0000000000000008 RDI: 0x0000000000000000 RSI: 0x0000000001e72cb8
  R8: 0x0000000000000001  R9: 0x0000000001e2c380 R10: 0x00007f5cb04a6f70
 R11: 0x0000000002252b90 R12: 0x00007fff1e970b20 R13: 0x00007fff1e970ad8
 R14: 0x00007f5cb04a6f20 R15: 0x0000000001e0a5f0 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(rb_vm_bugreport+0x4ea) [0x7f5caffa459a] vm_dump.c:693
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(rb_bug_context+0xcb) [0x7f5cafe3b09b] error.c:389
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(sigsegv+0x52) [0x7f5caff18f62] signal.c:878
/usr/lib/libpthread.so.0 [0x7f5cafbb1210]
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(rb_hash_lookup2+0x8) [0x7f5cafe6a9c8] hash.c:720
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(vm_call_method+0x37a) [0x7f5caff9dbba] vm_insnhelper.c:1606
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(vm_exec_core+0x29a7) [0x7f5caff92987] insns.def:2139
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(vm_exec+0x78) [0x7f5caff95798] vm.c:1407
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(rb_iseq_eval_main+0x203) [0x7f5caff972d3] vm.c:1677
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(ruby_exec_internal+0xbf) [0x7f5cafe4063f] eval.c:252
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(ruby_exec_node+0x1d) [0x7f5cafe429ad] eval.c:317
/home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2(ruby_run_node+0x1e) [0x7f5cafe4526e] eval.c:309
/home/rk/.rvm/rubies/ruby-2.2.0/bin/ruby(main+0x4b) [0x40089b] main.c:36

-- Other runtime information -----------------------------------------------

* Loaded script: hell_test.rb

* Loaded features:

    0 enumerator.so
    1 rational.so
    2 complex.so
    3 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
    4 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
    5 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/unicode_normalize.rb
    6 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/rbconfig.rb
    7 thread.rb
    8 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/thread.so
    9 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/compatibility.rb
   10 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/defaults.rb
   11 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/deprecate.rb
   12 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/errors.rb
   13 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/version.rb
   14 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/requirement.rb
   15 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/platform.rb
   16 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/basic_specification.rb
   17 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/stub_specification.rb
   18 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/util/stringio.rb
   19 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/specification.rb
   20 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/exceptions.rb
   21 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_gem.rb
   22 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/monitor.rb
   23 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb
   24 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems.rb
   25 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/path_support.rb
   26 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/dependency.rb
   27 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/attribute.rb
   28 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/fixture.rb
   29 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/exception-handler.rb
   30 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/assertion-failed-error.rb
   31 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/util/backtracefilter.rb
   32 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/util/method-owner-finder.rb
   33 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/diff.rb
   34 /home/rk/.rvm/gems/ruby-2.2.0@global/gems/power_assert-0.2.2/lib/power_assert/version.rb
   35 /home/rk/.rvm/gems/ruby-2.2.0@global/gems/power_assert-0.2.2/lib/power_assert/enable_tracepoint_events.rb
   36 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/ripper.so
   37 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/ripper/core.rb
   38 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/ripper/lexer.rb
   39 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/ripper/filter.rb
   40 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/ripper/sexp.rb
   41 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/ripper.rb
   42 /home/rk/.rvm/gems/ruby-2.2.0@global/gems/power_assert-0.2.2/lib/power_assert.rb
   43 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/assertions.rb
   44 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/failure.rb
   45 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/error.rb
   46 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/pending.rb
   47 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/omission.rb
   48 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/notification.rb
   49 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/etc.so
   50 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/fileutils.rb
   51 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/priority.rb
   52 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/data.rb
   53 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/testsuite.rb
   54 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/test-suite-creator.rb
   55 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/util/output.rb
   56 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/testcase.rb
   57 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/color.rb
   58 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/color-scheme.rb
   59 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/attribute-matcher.rb
   60 /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/optparse.rb
   61 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/runner/console.rb
   62 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/runner/emacs.rb
   63 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/runner/xml.rb
   64 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit/autorunner.rb
   65 /home/rk/.rvm/gems/ruby-2.2.0@soft24/gems/test-unit-3.0.9/lib/test/unit.rb

* Process memory map:

00400000-00401000 r-xp 00000000 08:01 804322                             /home/rk/.rvm/rubies/ruby-2.2.0/bin/ruby
00600000-00601000 rw-p 00000000 08:01 804322                             /home/rk/.rvm/rubies/ruby-2.2.0/bin/ruby
01e09000-026ac000 rw-p 00000000 00:00 0                                  [heap]
7f5cad280000-7f5cadf37000 r--s 00000000 08:01 131347                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2.0
7f5cadf37000-7f5cadf4d000 r-xp 00000000 08:01 527824                     /usr/lib/libgcc_s.so.1
7f5cadf4d000-7f5cae14c000 ---p 00016000 08:01 527824                     /usr/lib/libgcc_s.so.1
7f5cae14c000-7f5cae14d000 rw-p 00015000 08:01 527824                     /usr/lib/libgcc_s.so.1
7f5cae14d000-7f5cae153000 r-xp 00000000 08:01 142847                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/etc.so
7f5cae153000-7f5cae352000 ---p 00006000 08:01 142847                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/etc.so
7f5cae352000-7f5cae353000 rw-p 00005000 08:01 142847                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/etc.so
7f5cae353000-7f5cae381000 r-xp 00000000 08:01 142857                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/ripper.so
7f5cae381000-7f5cae581000 ---p 0002e000 08:01 142857                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/ripper.so
7f5cae581000-7f5cae583000 rw-p 0002e000 08:01 142857                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/ripper.so
7f5cae583000-7f5cae586000 r-xp 00000000 08:01 142856                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/thread.so
7f5cae586000-7f5cae786000 ---p 00003000 08:01 142856                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/thread.so
7f5cae786000-7f5cae787000 rw-p 00003000 08:01 142856                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/thread.so
7f5cae787000-7f5cae789000 r-xp 00000000 08:01 142807                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f5cae789000-7f5cae989000 ---p 00002000 08:01 142807                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f5cae989000-7f5cae98a000 rw-p 00002000 08:01 142807                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/trans/transdb.so
7f5cae98a000-7f5cae98c000 r-xp 00000000 08:01 142821                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f5cae98c000-7f5caeb8b000 ---p 00002000 08:01 142821                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f5caeb8b000-7f5caeb8c000 rw-p 00001000 08:01 142821                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/enc/encdb.so
7f5caeb8c000-7f5caee46000 r--p 00000000 08:01 549823                     /usr/lib/locale/locale-archive
7f5caee46000-7f5caefdf000 r-xp 00000000 08:01 527488                     /usr/lib/libc-2.20.so
7f5caefdf000-7f5caf1df000 ---p 00199000 08:01 527488                     /usr/lib/libc-2.20.so
7f5caf1df000-7f5caf1e3000 r--p 00199000 08:01 527488                     /usr/lib/libc-2.20.so
7f5caf1e3000-7f5caf1e5000 rw-p 0019d000 08:01 527488                     /usr/lib/libc-2.20.so
7f5caf1e5000-7f5caf1e9000 rw-p 00000000 00:00 0
7f5caf1e9000-7f5caf2ec000 r-xp 00000000 08:01 527487                     /usr/lib/libm-2.20.so
7f5caf2ec000-7f5caf4ec000 ---p 00103000 08:01 527487                     /usr/lib/libm-2.20.so
7f5caf4ec000-7f5caf4ed000 r--p 00103000 08:01 527487                     /usr/lib/libm-2.20.so
7f5caf4ed000-7f5caf4ee000 rw-p 00104000 08:01 527487                     /usr/lib/libm-2.20.so
7f5caf4ee000-7f5caf4f6000 r-xp 00000000 08:01 527504                     /usr/lib/libcrypt-2.20.so
7f5caf4f6000-7f5caf6f6000 ---p 00008000 08:01 527504                     /usr/lib/libcrypt-2.20.so
7f5caf6f6000-7f5caf6f7000 r--p 00008000 08:01 527504                     /usr/lib/libcrypt-2.20.so
7f5caf6f7000-7f5caf6f8000 rw-p 00009000 08:01 527504                     /usr/lib/libcrypt-2.20.so
7f5caf6f8000-7f5caf726000 rw-p 00000000 00:00 0
7f5caf726000-7f5caf729000 r-xp 00000000 08:01 527460                     /usr/lib/libdl-2.20.so
7f5caf729000-7f5caf928000 ---p 00003000 08:01 527460                     /usr/lib/libdl-2.20.so
7f5caf928000-7f5caf929000 r--p 00002000 08:01 527460                     /usr/lib/libdl-2.20.so
7f5caf929000-7f5caf92a000 rw-p 00003000 08:01 527460                     /usr/lib/libdl-2.20.so
7f5caf92a000-7f5caf9a0000 r-xp 00000000 08:01 535374                     /usr/lib/libgmp.so.10.2.0
7f5caf9a0000-7f5cafb9f000 ---p 00076000 08:01 535374                     /usr/lib/libgmp.so.10.2.0
7f5cafb9f000-7f5cafba0000 r--p 00075000 08:01 535374                     /usr/lib/libgmp.so.10.2.0
7f5cafba0000-7f5cafba1000 rw-p 00076000 08:01 535374                     /usr/lib/libgmp.so.10.2.0
7f5cafba1000-7f5cafbb8000 r-xp 00000000 08:01 527467                     /usr/lib/libpthread-2.20.so
7f5cafbb8000-7f5cafdb7000 ---p 00017000 08:01 527467                     /usr/lib/libpthread-2.20.so
7f5cafdb7000-7f5cafdb8000 r--p 00016000 08:01 527467                     /usr/lib/libpthread-2.20.so
7f5cafdb8000-7f5cafdb9000 rw-p 00017000 08:01 527467                     /usr/lib/libpthread-2.20.so
7f5cafdb9000-7f5cafdbd000 rw-p 00000000 00:00 0
7f5cafdbd000-7f5cb007e000 r-xp 00000000 08:01 131347                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2.0
7f5cb007e000-7f5cb027e000 ---p 002c1000 08:01 131347                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2.0
7f5cb027e000-7f5cb0286000 rw-p 002c1000 08:01 131347                     /home/rk/.rvm/rubies/ruby-2.2.0/lib/libruby.so.2.2.0
7f5cb0286000-7f5cb0297000 rw-p 00000000 00:00 0
7f5cb0297000-7f5cb02b9000 r-xp 00000000 08:01 527464                     /usr/lib/ld-2.20.so
7f5cb0363000-7f5cb0385000 r--s 00000000 08:01 527467                     /usr/lib/libpthread-2.20.so
7f5cb0385000-7f5cb03a7000 r--s 00000000 08:01 804322                     /home/rk/.rvm/rubies/ruby-2.2.0/bin/ruby
7f5cb03a7000-7f5cb04ad000 rw-p 00000000 00:00 0
7f5cb04b2000-7f5cb04b3000 rw-p 00000000 00:00 0
7f5cb04b3000-7f5cb04b4000 ---p 00000000 00:00 0
7f5cb04b4000-7f5cb04b8000 rw-p 00000000 00:00 0                          [stack:19103]
7f5cb04b8000-7f5cb04b9000 r--p 00021000 08:01 527464                     /usr/lib/ld-2.20.so
7f5cb04b9000-7f5cb04ba000 rw-p 00022000 08:01 527464                     /usr/lib/ld-2.20.so
7f5cb04ba000-7f5cb04bb000 rw-p 00000000 00:00 0
7fff1e952000-7fff1e973000 rw-p 00000000 00:00 0
7fff1e9bd000-7fff1e9bf000 r--p 00000000 00:00 0                          [vvar]
7fff1e9bf000-7fff1e9c1000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]


[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

Аварийный останов (core dumped)
```

**Comment by kou** [comment]
Thanks for your report.

I've confirmed it with Ruby 2.2.0 on my environment.
And I've also confirmed that it's not reproduced with Ruby trunk on my environment. It seems that the problem has been fixed at trunk.

Could you find the bug report of the problem at http://bugs.ruby-lang.org/ and sends a backport request? Then Ruby 2.2.0-pXXX or Ruby 2.2.1 will include the fix.

**Comment by kou** [comment]
I tried it with self build Ruby 2.2.0 and I couldn't reproduce it. This problem may be related build options and not be fixed at Ruby trunk.
Could you report it to http://bugs.ruby-lang.org/ ?
