### ISSUE TITLE
testrunner - NoMethodError: undefined method `assert_raise_with_message?'

### ISSUE THREAD

**Issue by pitbulk** [test-unit/test-unit#94]
Hi, I experienced a NoMethodError: undefined method `assert_raise_with_message?' 

My environment.
ruby-2.1.2
test-unit 3.0.9
rails 4

Stack-trace when running bundle exec rake

```test
Error: test: Response #validate should raise when there is no valid audience. (RubyTest)
: NoMethodError: undefined method `assert_raise_with_message' for #RubyTest:0x000000041f2c10>
/home/machine/xxxxxx/test/response_test.rb:121:in `block (3 levels) in <class:RubyTest>'
/home/machine/.rvm/gems/ruby-2.1.2@rails4/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in `call'
/home/machine/.rvm/gems/ruby-2.1.2@rails4/gems/shoulda-2.11.3/lib/shoulda/context.rb:382:in `block in create_test_from_should_hash'
```

Example to reproduce it:
```
    context "#validate" do
      should "raise an exception" do
          assert_raise_with_message(RuntimeError, "foo") do
              raise "foo"
          end
      end
```

**Comment by kou** [comment]
Use `assert_raise` with exception object (not exception class):

```ruby
assert_raise(RuntimeError.new("foo")) do
  raise "foo"
end
```

`assert_raise_with_message` is added by `test/unit` as minitest wrapper bundled in Ruby 1.9, 2.0 and 2.1. test-unit gem doesn't have `assert_raise_with_message`. test-unit gem provides `assert_raise(exception_object)` instead.
