### ISSUE TITLE
assert_block returns just nil

### ISSUE THREAD

**Issue by voxik** [test-unit/test-unit#99]
I am not sure this was ever intended to work:

```
$ cat test.rb 
require 'test/unit'

class TestAssertBlock < Test::Unit::TestCase

  def test_assert_block
    assert(assert_block { true })
  end

end

$ ruby test.rb 
Loaded suite test
Started
F
===================================================================================================================================================================================================================
Failure: <nil> is not true.
test_assert_block(TestAssertBlock)
test.rb:6:in `test_assert_block'
     3: class TestAssertBlock < Test::Unit::TestCase
     4: 
     5:   def test_assert_block
  => 6:     assert(assert_block { true })
     7:   end
     8: 
     9: end
===================================================================================================================================================================================================================


Finished in 0.003978268 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 2 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
251.37 tests/s, 502.73 assertions/s
```

Nevertheless, according to documentation [1], it should probably return something more. Moreover, the test-unit wrapper in Ruby 2.1 and older used to return true when the block succeeded.

I am asking, since I am trying to put Subversion's test suite into the shape and make it work with Ruby 2.2 and it fails like:

```
Failure: assert_block failed.
test_translated_file_eol(SvnWcTest)
/builddir/build/BUILD/subversion-1.8.11/subversion/bindings/swig/ruby/test/my-assertions.rb:30:in `_my_assert_block'
test/test_wc.rb:537:in `block (2 levels) in assert_translated_eol'
/builddir/build/BUILD/subversion-1.8.11/subversion/bindings/swig/ruby/svn/wc.rb:136:in `_open'
/builddir/build/BUILD/subversion-1.8.11/subversion/bindings/swig/ruby/svn/wc.rb:113:in `open'
test/test_wc.rb:536:in `block in assert_translated_eol'
/builddir/build/BUILD/subversion-1.8.11/subversion/bindings/swig/ruby/test/util.rb:240:in `make_context'
test/test_wc.rb:525:in `assert_translated_eol'
test/test_wc.rb:560:in `test_translated_file_eol'
     557:   end
     558: 
     559:   def test_translated_file_eol
  => 560:     assert_translated_eol(:translated_file) do |name, source|
     561:       File.open(name, "rb") {|f| f.read}
     562:     end
     563:   end
```

The test suite was designed above test-unit/minitest wrapper though.

[1] http://www.rubydoc.info/gems/test-unit/Test/Unit/Assertions#assert_block-instance_method
[2] https://svn.apache.org/viewvc/subversion/trunk/subversion/bindings/swig/ruby/test/test_wc.rb?revision=1467191&view=markup

**Comment by voxik** [comment]
The cure would be easy as return something meaningful from [1], e.g:

```ruby
 def assert_block(message="assert_block failed.")
  _wrap_assertion do
    if (! yield)
      raise AssertionFailedError.new(message.to_s)
    else
      true
    end
  end
end
```

[1] https://github.com/test-unit/test-unit/blob/3.0.9/lib/test/unit/assertions.rb#L53

**Comment by kou** [comment]
Wow! [2] is the file that was added by 10 years ago!

In this case, test code for Subversion Ruby bindings should be fixed.

`_wrap_assertion` was used just for counting multiple assertions as one assertion. `_wrap_assertion` is a feature of test-unit. It doesn't exist in minitest. minitest doesn't provide the feature. So we can't "count multiple assertions as one assertion" with minitest. The feature is just for good summary at the end of test. So it's OK that we just doesn't use the feature with minitest.

Could you send the following patch to Subversion developers? `assert_block` is meaningless because `assert_block` in minitest doesn't provide "counting multiple assertions as one assertion" feature.

```diff
Index: subversion/bindings/swig/ruby/test/my-assertions.rb
===================================================================
--- subversion/bindings/swig/ruby/test/my-assertions.rb	(revision 1671827)
+++ subversion/bindings/swig/ruby/test/my-assertions.rb	(working copy)
@@ -27,9 +27,7 @@
       # make an intermediary assertion block handler
       def _my_assert_block(&block)
        if RUBY_VERSION > '1.9'
-         assert_block do
-           yield
-         end
+         yield
        else
          _wrap_assertion do
            yield
```

Furthermore, we can remove `_my_assert_block` like the following because Ruby 1.8 is end of life and "counting multiple assertions as one assertion" isn't required test feature:

```diff
Index: subversion/bindings/swig/ruby/test/my-assertions.rb
===================================================================
--- subversion/bindings/swig/ruby/test/my-assertions.rb	(revision 1671827)
+++ subversion/bindings/swig/ruby/test/my-assertions.rb	(working copy)
@@ -24,56 +24,35 @@
   module Unit
     module Assertions
 
-      # make an intermediary assertion block handler
-      def _my_assert_block(&block)
-       if RUBY_VERSION > '1.9'
-         assert_block do
-           yield
-         end
-       else
-         _wrap_assertion do
-           yield
-         end
-       end
-      end
-
       def assert_true(boolean, message=nil)
-        _my_assert_block do
-          assert_equal(true, boolean, message)
-        end
+        assert_equal(true, boolean, message)
       end
 
       def assert_false(boolean, message=nil)
-        _my_assert_block do
-          assert_equal(false, boolean, message)
-        end
+        assert_equal(false, boolean, message)
       end
 
       def assert_nested_sorted_array(expected, actual, message=nil)
-        _my_assert_block do
-          assert_equal(expected.collect {|elem| elem.sort},
-                       actual.collect {|elem| elem.sort},
-                       message)
-        end
+        assert_equal(expected.collect {|elem| elem.sort},
+                     actual.collect {|elem| elem.sort},
+                     message)
       end
 
       def assert_equal_log_entries(expected, actual, message=nil)
-        _my_assert_block do
-          actual = actual.collect do |entry|
-            changed_paths = entry.changed_paths
-            changed_paths.each_key do |path|
-              changed_path = changed_paths[path]
-              changed_paths[path] = [changed_path.action,
-                                     changed_path.copyfrom_path,
-                                     changed_path.copyfrom_rev]
-            end
-            [changed_paths,
-             entry.revision,
-             entry.revision_properties.reject {|key, value| key == "svn:date"},
-             entry.has_children?]
+        actual = actual.collect do |entry|
+          changed_paths = entry.changed_paths
+          changed_paths.each_key do |path|
+            changed_path = changed_paths[path]
+            changed_paths[path] = [changed_path.action,
+                                   changed_path.copyfrom_path,
+                                   changed_path.copyfrom_rev]
           end
-          assert_equal(expected, actual, message)
+          [changed_paths,
+           entry.revision,
+           entry.revision_properties.reject {|key, value| key == "svn:date"},
+           entry.has_children?]
         end
+        assert_equal(expected, actual, message)
       end
     end
   end
```

**Comment by voxik** [comment]
> Wow! [2] is the file that was added by 10 years ago!

Yep, there were days when SVN was popular ;)

Thanks for hints. I will prepare patch for Fedora and discuss with Fedora's maintainer. If I am not mistaken, he has upstream commit bit.

**Comment by kou** [comment]
>> Wow! [2] is the file that was added by 10 years ago!
> 
> Yep, there were days when SVN was popular ;)

(Oh... "me" is missing before "by"... The file was added by me 10 years ago. I'm the original author of the Ruby bindings of Subversion. ;-))

> Thanks for hints. I will prepare patch for Fedora and discuss with Fedora's maintainer. If I am not mistaken, he has upstream commit bit.

Thanks! It's very helpful!
